### ISSUE TITLE
Join to Crystal Tools organization

### ISSUE THREAD

**Issue by faustinoaq** [g3ortega/vscode-crystal#5]
Hi @g3ortega, some Crystal community members have the idea of a [Crystal Tools organization](https://github.com/crystal-lang-tools) inspired by [Julia Editor Support organization](https://github.com/JuliaEditorSupport).

We are adding repositories for sublime, emacs, vim, vscode, atom, etc. All in one place well documented easy to follow, collaborate and maintain. :-)

If you accept the proposal of move your repo to Crystal Tool organization, leave a message in [Gitter room](https://gitter.im/crystal-scry/Lobby?source=orgpage) first.

You were the first person on create a vscode extension for crystal. In fact [my extension](https://github.com/faustinoaq/vscode-crystal-lang) syntax and snippets are inspired by this extension. So, feel free to join to Crystal organization.

Thanks you for your vscode extension for Crystal. 💓

**Comment by g3ortega** [comment]
Hi @faustinoaq,  would be a pleasure to collaborate with you in the community created, great idea btw

**Comment by keplersj** [comment]
Your invitation to join the `vscode` team in the crystal-lang-tool organization has been sent. Welcome! Please reach out to either myself or @faustinoaq if you have any questions.

**Comment by g3ortega** [comment]
Thanks @keplersj and @faustinoaq, I will be in touch soon to see where I may help!

**Comment by g3ortega** [comment]
btw, I will modify the readme to reference vscode-crystal-lang. And focus in the development and maintainance of [vscode-crystal-lang](https://github.com/crystal-lang-tools/vscode-crystal-lang) library for VSCode

**Comment by faustinoaq** [comment]
You are on Crystal tool organization now, so I'm closing this :sweat_smile:
